function PTperBlock(Np, nFsDown)
if nargin < 1
    Np = 4;
end
if nargin < 2
    nFsDown = 20;
end

warning('off','MATLAB:xlswrite:AddSheet');

postreviewFig = figure('MenuBar', 'None', 'Units', 'normalized', 'Name', 'perBlock', ...
    'Position', [0.0 0.03 1 0.92], 'NumberTitle', 'off');

hndl = get(postreviewFig, 'Userdata');

hndl.postreviewFig = postreviewFig;

hndl.general.setting.FsP = (24414.0625*Np/nFsDown);

hndl.general.file.FileN = 'None';
hndl.general.file.PathN = 'C:\AMFR\Data';
hndl.general.file.PathNRe = 'C:\AMFR\perBlock';

hndl.uipanel.file_PN = uipanel('Title', '', 'Fontsize', 12, ...
    'Units', 'normalized', 'Position', [0.0 0.85 1 0.15], 'TitlePosition', 'centertop', ...
    'BackgroundColor', [0.9 0.9 0.9], 'BorderType', 'etchedout', 'BorderWidth', 2);

hndl.uicontrol.control.GetFileN = uicontrol('Parent', hndl.uipanel.file_PN, ...
    'Style', 'pushbutton', 'String', 'Select File Name', ...
    'Units', 'normalized', 'Userdata', 1, ...
    'Fontsize', 12, 'Position', [0.05 0.55 0.3 0.4], ...
    'Callback', {@PGetFileN_prs, 1});

hndl.uicontrol.control.FileNameT = uicontrol('Parent', hndl.uipanel.file_PN, ...
    'Style', 'text', 'String', 'File Name', 'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.05 0.05 0.2 0.4]);

hndl.uicontrol.control.FileName = uicontrol('Parent', hndl.uipanel.file_PN, ...
    'Style', 'edit', 'String', hndl.general.file.FileN, ...
    'Units', 'normalized', 'Enable', 'off', ...
    'Fontsize', 12, 'Position', [0.25 0.05 0.7 0.4], ...
    'Callback', {@PGetFileN_prs, 2});

hndl.uicontrol.control.PathNameT = uicontrol('Parent', hndl.uipanel.file_PN, ...
    'Style', 'text', 'String', 'Folder Path', 'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.4 0.55 0.2 0.4]);

hndl.uicontrol.control.PathName = uicontrol('Parent', hndl.uipanel.file_PN, ...
    'Style', 'edit', 'String', hndl.general.file.PathN, ...
    'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.6 0.55 0.35 0.4], ...
    'Callback', {@PGetFileN_prs, 3});

hndl.uipanel.criteria_PN = uipanel('Title', '', 'Fontsize', 12, ...
    'Units', 'normalized', 'Position', [0.0 0.25 0.4 0.6], 'TitlePosition', 'centertop', ...
    'BackgroundColor', [0.9 0.9 0.9], 'BorderType', 'etchedout', 'BorderWidth', 2);

hndl.setting.criteria.selection = [1, 1, 0];

hndl.uicontrol.control.criteria_CK = zeros(1, 3);

hndl.uicontrol.control.criteria_CK(1) = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'checkbox', 'String', 'Criteria 1', ...
    'Units', 'normalized', 'Value', hndl.setting.criteria.selection(1), ...
    'Fontsize', 12, 'Position', [0.05 0.9 0.2 0.08], ...
    'Callback', {@PcriteriaCK_prs, 1});

hndl.setting.criteria.cohz = 0.25;

hndl.uicontrol.control.COHZ_TX = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'text', 'String', 'cohere >= ', 'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.27 0.9 0.2 0.08]);

hndl.uicontrol.control.COHZ_ED = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'edit', 'String', hndl.setting.criteria.cohz, ...
    'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.47 0.9 0.1 0.08], ...
    'Callback', @PCOHZ_ED_prs);

hndl.setting.criteria.Zsd = 3;

hndl.uicontrol.control.ZSD_TX = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'text', 'String', 'AND strength(Z)>= ', 'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.57 0.9 0.3 0.08]);

hndl.uicontrol.control.ZSD_ED = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'edit', 'String', hndl.setting.criteria.Zsd, ...
    'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.87 0.9 0.1 0.08], ...
    'Callback', @PZSD_prs);

hndl.uicontrol.control.criteria_CK(2) = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'checkbox', 'String', 'Criteria 2', ...
    'Units', 'normalized', 'Value', hndl.setting.criteria.selection(2), ...
    'Fontsize', 12, 'Position', [0.05 0.8 0.2 0.08], ...
    'Callback', {@PcriteriaCK_prs, 2});

hndl.setting.criteria.coha = 0.5;

hndl.uicontrol.control.COHA_TX = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'text', 'String', 'OR cohere >= ', 'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.27 0.8 0.3 0.08]);

hndl.uicontrol.control.COHA_ED = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'edit', 'String', hndl.setting.criteria.coha, ...
    'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.57 0.8 0.1 0.08], ...
    'Callback', @PCOHA_ED_prs);

hndl.uicontrol.control.criteria_CK(3) = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'checkbox', 'String', 'Criteria 3', ...
    'Units', 'normalized', 'Value', hndl.setting.criteria.selection(3), ...
    'Fontsize', 12, 'Position', [0.05 0.7 0.2 0.08], ...
    'Callback', {@PcriteriaCK_prs, 3});

hndl.setting.criteria.Zsda = 30;

hndl.uicontrol.control.ZsdA_TX = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'text', 'String', 'OR strength(Z)>', 'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.27 0.7 0.3 0.08]);

hndl.uicontrol.control.ZsdA_ED = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'edit', 'String', hndl.setting.criteria.Zsda, ...
    'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.57 0.7 0.1 0.08], ...
    'Callback', @PZsdA_ED_prs);

hndl.setting.criteria.perBlock = 20;

hndl.uicontrol.control.perBlocks_TX = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'text', 'String', '# of Epochs per Block', 'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.1 0.6 0.6 0.08]);

hndl.uicontrol.control.perBlocks_ED = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'edit', 'String', hndl.setting.criteria.perBlock, ...
    'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.7 0.6 0.1 0.08], ...
    'Callback', @PTBlocks_ED_prs);

hndl.setting.criteria.NCriteria = 6;

hndl.uicontrol.control.NCriteria_TX = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'text', 'String', '# of Criteria (<= 6)', 'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.1 0.5 0.6 0.08]);

hndl.uicontrol.control.NCriteria_ED = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'edit', 'String', hndl.setting.criteria.NCriteria, ...
    'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.7 0.5 0.1 0.08], ...
    'Callback', @PCriteria_ED_prs);

hndl.uicontrol.control.Nbin_TX = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
    'Style', 'text', 'String', '# of bins used around Mod Freq to generate MEAN or STD:', 'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.0 0.41 1 0.08]);

hndl.setting.criteria.NPoints = zeros(6, 6);
hndl.setting.criteria.NPoints(1, :) = [3 1 0 3 0 6];
hndl.setting.criteria.NPoints(2, :) = [3 1 3 3 3 3];
hndl.setting.criteria.NPoints(3, :) = [1 2 0 3 0 6];
hndl.setting.criteria.NPoints(4, :) = [1 2 3 3 3 3];
hndl.setting.criteria.NPoints(5, :) = [1 3 0 3 0 6];
hndl.setting.criteria.NPoints(6, :) = [1 3 3 3 3 3];

hndl.uicontrol.control.NUI_TX = zeros(1, 6);
hndl.uicontrol.control.NUI_ED = zeros(6, 6);

strT = {'#COH', '#OMIT', '#DIFFL', '#DIFFR', '#SDL', '#SDR'};

for nnn = 1:6

    hndl.uicontrol.control.NUI_TX(nnn) = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
        'Style', 'text', 'String', strT{nnn}, 'Units', 'normalized', ...
        'Fontsize', 12, 'Position', [0.02 + (nnn-1)*0.16 0.35 0.15 0.05]);

    for mmm = 1:6

        hndl.uicontrol.control.NUI_ED(mmm, nnn) = uicontrol('Parent', hndl.uipanel.criteria_PN, ...
            'Style', 'edit', 'String', hndl.setting.criteria.NPoints(mmm, nnn), ...
            'Units', 'normalized', ...
            'Fontsize', 12, 'Position', [0.02 + (nnn-1)*0.16 0.29-(mmm-1)*0.05 0.15 0.05], ...
            'Callback', {@PPoints_ED_prs, mmm, nnn});
    end
end

hndl.uipanel.general_PN = uipanel('Title', '', 'Fontsize', 12, ...
    'Units', 'normalized', 'Position', [0.4 0.25 0.6 0.6], 'TitlePosition', 'centertop', ...
    'BackgroundColor', [0.9 0.9 0.9], 'BorderType', 'etchedout', 'BorderWidth', 2);

hndl.general.setting.mf = 42.9;

hndl.uicontrol.control.mf_TX = uicontrol('Parent', hndl.uipanel.general_PN, ...
    'Style', 'text', 'String', 'Modulation Frequency', 'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.05 0.88 0.3 0.1]);

hndl.uicontrol.control.mf_ED = uicontrol('Parent', hndl.uipanel.general_PN, ...
    'Style', 'edit', 'String', hndl.general.setting.mf, ...
    'Units', 'normalized', 'Enable', 'off', ...
    'Fontsize', 12, 'Position', [0.35 0.88 0.1 0.1], ...
    'Callback', @Pmf_ED_prs);

hndl.general.setting.bandwidth = 1;

hndl.uicontrol.control.bandwidth_TX = uicontrol('Parent', hndl.uipanel.general_PN, ...
    'Style', 'text', 'String', 'Band Width (#octave)', 'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.55 0.88 0.3 0.1]);

hndl.uicontrol.control.bandwidth_ED = uicontrol('Parent', hndl.uipanel.general_PN, ...
    'Style', 'edit', 'String', hndl.general.setting.bandwidth, ...
    'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.85 0.88 0.1 0.1], ...
    'Callback', @Pbandwidth_ED_prs);

hndl.uicontrol.control.coherenceN = uicontrol('Parent', hndl.uipanel.general_PN, ...
    'Style', 'pushbutton', 'String', 'Coherence', ...
    'Units', 'normalized', 'Userdata', 1, ...
    'Fontsize', 12, 'Position', [0.025 0.75 0.2 0.11], ...
    'Callback', @PTcoherenceN_prs2);

hndl.uicontrol.control.FFTN = uicontrol('Parent', hndl.uipanel.general_PN, ...
    'Style', 'pushbutton', 'String', 'Frequency Averaged', ...
    'Units', 'normalized', 'Userdata', 1, ...
    'Fontsize', 12, 'Position', [0.275 0.75 0.2 0.11], ...
    'Callback', @PTFFTN_prs2);

hndl.uicontrol.control.waveN = uicontrol('Parent', hndl.uipanel.general_PN, ...
    'Style', 'pushbutton', 'String', 'Waveform Averaged', ...
    'Units', 'normalized', 'Userdata', 1, ...
    'Fontsize', 12, 'Position', [0.525 0.75 0.2 0.11], ...
    'Callback', @PTwaveN_prs2);

hndl.uicontrol.control.phaseN = uicontrol('Parent', hndl.uipanel.general_PN, ...
    'Style', 'pushbutton', 'String', 'Phase Averaged', ...
    'Units', 'normalized', 'Userdata', 1, ...
    'Fontsize', 12, 'Position', [0.775 0.75 0.2 0.11], ...
    'Callback', @PTPhaseN_prs2);

hndl.uicontrol.control.headLine_TX = uicontrol('Parent', hndl.uipanel.general_PN, ...
    'Style', 'text', 'String', 'Head Line', 'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.0 0.65 1 0.08]);


hndl.uicontrol.plots.display_AX = axes('Parent', hndl.uipanel.general_PN, ...
    'Units', 'normalized', ...
    'Fontsize', 12, 'Position', [0.1 0.1 0.8 0.5]);

hndl.uipanel.display_PN = uipanel('Title', '', 'Fontsize', 12, ...
    'Units', 'normalized', 'Position', [0.0 0.05 1 0.2], 'TitlePosition', 'centertop', ...
    'BackgroundColor', [0.9 0.9 0.9], 'BorderType', 'etchedout', 'BorderWidth', 2);

hndl.uicontrol.control.display_ED = uicontrol('Parent', hndl.uipanel.display_PN, ...
    'Style', 'edit', 'String', '', ...
    'Units', 'normalized', 'max', 3, ...
    'Fontsize', 12, 'Position', [0.02 0.05 0.98 0.9]);


set(hndl.postreviewFig, 'Userdata', hndl);